"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^b2grjf(fl)c)f18sfih!r31vu9vphoj&2%9n_pmkkugt6)m=4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    'corsheaders',

    # Local apps
    'core',
    'competitions',
    'teams',
    'matches',
    'players',
    'stats',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:5174",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "hkenewdb",
        "USER": "root",
        "PASSWORD": "",
        "HOST": "localhost",
        "PORT": "3306",
        "OPTIONS": {
            "charset": "utf8mb4",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#Jazzmin settings
JAZZMIN_SETTINGS = {
    "site_title": "HockeyKE Admin",
    "site_header": "HockeyKE",
    "site_brand": "HockeyKE",

    "welcome_sign": "Welcome to HockeyKE Admin",
    "copyright": "HockeyKE",

    "show_sidebar": True,
    "navigation_expanded": True,

    "order_with_respect_to": [
        "competitions",
        "competitions.Season",
        "competitions.League",
        "competitions.LeagueSeason",

        "teams",
        "teams.MenTeam",
        "teams.WomenTeam",
        "teams.TeamLeagueSeason",

        "players",

        "matches",
        "matches.Match",
        "matches.PremierLeagueMenMatch",
        "matches.SuperLeagueMenMatch",
        "matches.NationalLeagueCentralZoneMatch",
        "matches.NationalLeagueEasternZoneMatch",
        "matches.NationalLeagueSouthernZoneMatch",
        "matches.NationalLeagueWesternZoneMatch",
        "matches.PremierLeagueWomenMatch",
        "matches.SuperLeagueWomenMatch",
        "matches.MatchEvent",

        "stats",
        "stats.Standings",
        "auth",
    ],

    "icons": {
        "competitions": "fas fa-trophy",
        "competitions.Season": "fas fa-calendar-alt",
        "competitions.League": "fas fa-medal",
        "competitions.LeagueSeason": "fas fa-layer-group",

        "teams": "fas fa-users",
        "teams.MenTeam": "fas fa-male",
        "teams.WomenTeam": "fas fa-female",
        "teams.TeamLeagueSeason": "fas fa-random",

        "players": "fas fa-user",
        "matches": "fas fa-calendar-check",
        "matches.Match": "fas fa-hockey-puck",
        "stats": "fas fa-chart-bar",

        "auth": "fas fa-users-cog",
        "auth.User": "fas fa-user-shield",
        "auth.Group": "fas fa-users-cog",
    },
}
