# Generated by Django 5.2.15 on 2026-06-16 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField()),
                ('match_time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('FT', 'Full Time'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('home_score', models.PositiveSmallIntegerField(default=0)),
                ('away_score', models.PositiveSmallIntegerField(default=0)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='teams.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='teams.team')),
                ('league_season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='competitions.leagueseason')),
            ],
            options={
                'ordering': ['match_date', 'match_time'],
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(blank=True, max_length=100)),
                ('event_type', models.CharField(choices=[('GOAL', 'Goal'), ('GREEN_CARD', 'Green Card'), ('YELLOW_CARD', 'Yellow Card'), ('RED_CARD', 'Red Card')], max_length=20)),
                ('minute', models.PositiveSmallIntegerField()),
                ('goal_type', models.CharField(blank=True, choices=[('FIELD_GOAL', 'Field Goal'), ('PENALTY_CORNER', 'Penalty Corner'), ('PENALTY_STROKE', 'Penalty Stroke')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matches.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teams.team')),
            ],
            options={
                'ordering': ['match', 'minute'],
            },
        ),
    ]
