# Generated by Django 5.2.15 on 2026-06-16 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['match_date', 'match_time'], 'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
    ]
