# Generated by Django 5.2.15 on 2026-06-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_match_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
