# Generated by Django 5.2.15 on 2026-06-17 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_match_match_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalLeagueCentralZoneMatch',
            fields=[
            ],
            options={
                'verbose_name': 'National League Central Zone Match',
                'verbose_name_plural': 'National League Central Zone Matches',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('matches.match',),
        ),
        migrations.CreateModel(
            name='NationalLeagueEasternZoneMatch',
            fields=[
            ],
            options={
                'verbose_name': 'National League Eastern Zone Match',
                'verbose_name_plural': 'National League Eastern Zone Matches',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('matches.match',),
        ),
        migrations.CreateModel(
            name='NationalLeagueSouthernZoneMatch',
            fields=[
            ],
            options={
                'verbose_name': 'National League Southern Zone Match',
                'verbose_name_plural': 'National League Southern Zone Matches',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('matches.match',),
        ),
        migrations.CreateModel(
            name='NationalLeagueWesternZoneMatch',
            fields=[
            ],
            options={
                'verbose_name': 'National League Western Zone Match',
                'verbose_name_plural': 'National League Western Zone Matches',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('matches.match',),
        ),
        migrations.CreateModel(
            name='PremierLeagueMenMatch',
            fields=[
            ],
            options={
                'verbose_name': 'Premier League Men Match',
                'verbose_name_plural': 'Premier League Men Matches',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('matches.match',),
        ),
        migrations.CreateModel(
            name='PremierLeagueWomenMatch',
            fields=[
            ],
            options={
                'verbose_name': 'Premier League Women Match',
                'verbose_name_plural': 'Premier League Women Matches',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('matches.match',),
        ),
        migrations.CreateModel(
            name='SuperLeagueMenMatch',
            fields=[
            ],
            options={
                'verbose_name': 'Super League Men Match',
                'verbose_name_plural': 'Super League Men Matches',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('matches.match',),
        ),
        migrations.CreateModel(
            name='SuperLeagueWomenMatch',
            fields=[
            ],
            options={
                'verbose_name': 'Super League Women Match',
                'verbose_name_plural': 'Super League Women Matches',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('matches.match',),
        ),
    ]
