# Generated by Django 5.2.15 on 2026-06-17 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_nationalleaguecentralzonematch_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nationalleaguecentralzonematch',
            options={'verbose_name': 'NLM-CZ Match', 'verbose_name_plural': 'NLM-CZ Matches'},
        ),
        migrations.AlterModelOptions(
            name='nationalleagueeasternzonematch',
            options={'verbose_name': 'NLM-EZ Match', 'verbose_name_plural': 'NLM-EZ Matches'},
        ),
        migrations.AlterModelOptions(
            name='nationalleaguesouthernzonematch',
            options={'verbose_name': 'NLM-SZ Match', 'verbose_name_plural': 'NLM-SZ Matches'},
        ),
        migrations.AlterModelOptions(
            name='nationalleaguewesternzonematch',
            options={'verbose_name': 'NLM-WZ Match', 'verbose_name_plural': 'NLM-WZ Matches'},
        ),
        migrations.AlterModelOptions(
            name='premierleaguemenmatch',
            options={'verbose_name': 'PLM Match', 'verbose_name_plural': 'Premier League Men Matches'},
        ),
        migrations.AlterModelOptions(
            name='premierleaguewomenmatch',
            options={'verbose_name': 'PLW Match', 'verbose_name_plural': 'PLW Matches'},
        ),
        migrations.AlterModelOptions(
            name='superleaguemenmatch',
            options={'verbose_name': 'SLM Match', 'verbose_name_plural': 'SLM Matches'},
        ),
        migrations.AlterModelOptions(
            name='superleaguewomenmatch',
            options={'verbose_name': 'SLW Match', 'verbose_name_plural': 'SLW Matches'},
        ),
    ]
