# Generated by Django 5.2.15 on 2026-06-17 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_alter_nationalleaguecentralzonematch_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['match_date', 'match_time'], 'verbose_name': 'All Matches', 'verbose_name_plural': 'All Matches'},
        ),
        migrations.AlterModelOptions(
            name='premierleaguemenmatch',
            options={'verbose_name': 'PLM Match', 'verbose_name_plural': 'PLM Matches'},
        ),
    ]
