# Generated by Django 5.2.15 on 2026-06-16 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=30)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamLeagueSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='competitions.leagueseason')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_memberships', to='teams.team')),
            ],
            options={
                'ordering': ['league_season', 'team__name'],
                'constraints': [models.UniqueConstraint(fields=('team', 'league_season'), name='uniq_team_league_season')],
            },
        ),
    ]
