# Generated by Django 5.2.15 on 2026-06-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='gender',
            field=models.CharField(blank=True, choices=[('MEN', 'Men'), ('WOMEN', 'Women')], max_length=10, null=True),
        ),
    ]
