# Generated by Django 5.2.15 on 2026-06-16 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenTeam',
            fields=[
            ],
            options={
                'verbose_name': 'Men Team',
                'verbose_name_plural': 'Men Teams',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('teams.team',),
        ),
        migrations.CreateModel(
            name='WomenTeam',
            fields=[
            ],
            options={
                'verbose_name': 'Women Team',
                'verbose_name_plural': 'Women Teams',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('teams.team',),
        ),
    ]
