# Generated by Django 5.2.15 on 2026-06-16 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('MEN', 'Men'), ('WOMEN', 'Women')], max_length=10)),
                ('division', models.CharField(blank=True, max_length=30)),
                ('zone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['name', 'gender', 'division', 'zone'],
                'constraints': [models.UniqueConstraint(fields=('name', 'gender', 'division', 'zone'), name='uniq_league')],
            },
        ),
        migrations.CreateModel(
            name='LeagueSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='league_seasons', to='competitions.league')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='league_seasons', to='competitions.season')),
            ],
            options={
                'ordering': ['-season__name', 'league__name'],
                'constraints': [models.UniqueConstraint(fields=('league', 'season'), name='uniq_league_season')],
            },
        ),
    ]
