# Generated by Django 5.2.15 on 2026-06-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'ordering': ['name', 'gender', 'zone']},
        ),
        migrations.RemoveConstraint(
            model_name='league',
            name='uniq_league',
        ),
        migrations.RemoveField(
            model_name='league',
            name='division',
        ),
        migrations.AddField(
            model_name='league',
            name='short_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='league',
            name='zone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddConstraint(
            model_name='league',
            constraint=models.UniqueConstraint(fields=('name', 'gender', 'zone'), name='uniq_league'),
        ),
    ]
