# Generated by Django 5.2.15 on 2026-06-17 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_alter_league_options_remove_league_uniq_league_and_more'),
        ('stats', '0001_initial'),
        ('teams', '0004_alter_team_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamstanding',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teamstanding',
            name='league_season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='competitions.leagueseason'),
        ),
        migrations.AddConstraint(
            model_name='teamstanding',
            constraint=models.UniqueConstraint(fields=('league_season', 'team'), name='uniq_team_standing'),
        ),
        migrations.RemoveField(
            model_name='teamstanding',
            name='league',
        ),
    ]
