# Generated by Django 5.2.15 on 2026-06-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_teamstanding_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Standings',
                'verbose_name_plural': 'Standings',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='TeamStanding',
        ),
    ]
